// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, cloudflare (build-only),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... } }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

// Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
// @cloudflare/vite-plugin builds from this — wrangler.jsonc main alone is insufficient.
//
// PWA / offline support (manifest.webmanifest, sw.js) is hand-written under public/ rather
// than generated by vite-plugin-pwa — that plugin's closeBundle hook only runs _generateSW()
// when `!ctx.viteConfig.build.ssr`, and this project's single `vite build` invocation builds
// both the client and ssr environments back to back (Vite's Environment API), which left that
// check permanently false and silently skipped service worker generation.
export default defineConfig({
  tanstackStart: {
    server: { entry: "server" },
  },
});
