// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, cloudflare (build-only),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... } }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

// Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
// @cloudflare/vite-plugin builds from this — wrangler.jsonc main alone is insufficient.
//
// PWA / offline support (manifest.webmanifest, sw.js) is hand-written under public/ rather
// than generated by vite-plugin-pwa — that plugin's closeBundle hook only runs _generateSW()
// when `!ctx.viteConfig.build.ssr`, and this project's single `vite build` invocation builds
// both the client and ssr environments back to back (Vite's Environment API), which left that
// check permanently false and silently skipped service worker generation.
export default defineConfig({
  tanstackStart: {
    server: { entry: "server" },
  },
  vite: {
    optimizeDeps: {
      // esbuild's dev-server pre-bundler rewrites these into .vite/deps/ cache
      // files, which breaks the Emscripten loader's import.meta.url-relative
      // fetch of its own .wasm binary ("both async and sync fetching of the
      // wasm failed"). Excluding them serves the real ES modules from
      // node_modules directly, where that relative path resolves correctly.
      // Vite's production build (Rollup) doesn't have this problem.
      exclude: ["quickjs-emscripten-core", "@jitl/quickjs-wasmfile-release-sync"],
      // Opposite problem, opposite fix: monaco-graphql's language worker
      // pulls in a few legacy CJS-only packages (via graphql-language-service)
      // that ship no ESM build. Inside a Worker's isolated module graph they
      // don't get esbuild's usual CJS→ESM interop shimming, which breaks with
      // e.g. "The requested module 'nullthrows' does not provide an export
      // named 'default'". Forcing them through esbuild's pre-bundler (which
      // does apply that interop) fixes it. Vite's production build (Rollup)
      // doesn't have this problem either.
      include: [
        "nullthrows",
        "debounce-promise",
        "vscode-languageserver-types",
        "picomatch-browser",
      ],
    },
  },
});
